repos:
    -   repo: local
        hooks:
            -   id: generate-readme
                name: Generate README.md from README.ipynb
                entry: jupyter nbconvert --execute --to markdown README.ipynb
                language: system
                always_run: true
                pass_filenames: false
